# stages/adls.stage.yml
parameters:
- name: adh_group
  type: string
  default: ''

- name: adh_sub_group
  type: string
  default: ''          # OPTIONAL – can be left empty

- name: adh_subscription_type
  type: string
  default: nonprd
  values:
    - nonprd
    - prd

- name: poolName
  type: string
  default: 'Self-Hosted-Pool'

- name: agentName
  type: string
  default: ''

stages:
- stage: adls_validation
  displayName: ${{ 
    eq(parameters.adh_sub_group, '') 
      ? format('ADLS ACL Validation ({0} / {1})', parameters.adh_group, parameters.adh_subscription_type) 
      : format('ADLS ACL Validation ({0}_{1} / {2})', parameters.adh_group, parameters.adh_sub_group, parameters.adh_subscription_type) 
    }}
  condition: and(succeeded(), ne('${{ parameters.adh_group }}',''))

  jobs:
  - template: ../templates/job.powershell-with-az.yml
    parameters:
      displayName: 'ADLS ACL Validation'
      variableGroup: modernization_tfstate_backend_details
      scriptPath: '$(Build.SourcesDirectory)/sanitychecks/scripts/Scan-ADLS-Acls.ps1'
      workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
      arguments: >-
        -TenantId "$(tenant_id)"
        -ClientId "$(backend_client_id)"
        -ClientSecret "$(backend_client_secret)"
        -adh_group "${{ parameters.adh_group }}"
        -adh_sub_group "${{ parameters.adh_sub_group }}"
        -adh_subscription_type "${{ parameters.adh_subscription_type }}"
        -InputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/adls_permissions.csv"
        -OutputDir "$(Build.ArtifactStagingDirectory)/adls-acl"
        -BranchName "$(Build.SourceBranchName)"
      artifactName: 'adls-acl-results'
      publishPath: '$(Build.ArtifactStagingDirectory)/adls-acl'
      poolName: ${{ parameters.poolName }}
      agentName: ${{ parameters.agentName }}
