parameters:
  - name: adh_group
    type: string
    default: ''

  - name: adh_sub_group
    type: string
    default: ''

  - name: adh_subscription_type
    type: string
    default: nonprd
    values: [nonprd, prd]

  - name: poolName
    type: string
    default: 'Self-Hosted-Pool'

  - name: agentName
    type: string
    default: ''

# Build custodian part safely
variables:
  custodian_full: >
    ${{ parameters.adh_group }}${{ ne(parameters.adh_sub_group, '') && format('_{0}', parameters.adh_sub_group) }}

stages:
- stage: rg_permissions
  displayName: "RG Permissions (${{ variables.custodian_full }} / ${{ parameters.adh_subscription_type }})"
  condition: and(succeeded(), ne('${{ parameters.adh_group }}',''))

  jobs:
  - template: ../templates/job.powershell-with-az.yml
    parameters:
      displayName: 'RG Permissions'
      variableGroup: modernization_tfstate_backend_details
      scriptPath: '$(Build.SourcesDirectory)/sanitychecks/scripts/Scan-RG-Permissions-ByCustodian.ps1'
      workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'

      arguments: >-
        -TenantId "$(tenant_id)"
        -ClientId "$(backend_client_id)"
        -ClientSecret "$(backend_client_secret)"
        -adh_group "${{ parameters.adh_group }}"
        -adh_sub_group "${{ parameters.adh_sub_group }}"
        -adh_subscription_type "${{ parameters.adh_subscription_type }}"
        -ProdCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/prod_permissions.csv"
        -NonProdCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/nonprod_permissions.csv"
        -OutputDir "$(Build.ArtifactStagingDirectory)/rg-permissions"
        -BranchName "$(Build.SourceBranchName)"

      artifactName: 'rg-permissions'
      publishPath: '$(Build.ArtifactStagingDirectory)/rg-permissions'
      poolName: ${{ parameters.poolName }}
      agentName: ${{ parameters.agentName }}
