parameters:
  - name: adh_group
    type: string
    default: ''

  - name: adh_sub_group            # <-- Added (optional)
    type: string
    default: ''

  - name: adh_subscription_type
    type: string
    default: nonprd
    values: [nonprd, prd]

  - name: poolName
    type: string
    default: 'Self-Hosted-Pool'

  - name: agentName
    type: string
    default: ''


stages:
- stage: rg_tags
  displayName: "RG Tags (${{ parameters.adh_group }}${{ parameters.adh_sub_group != '' && format('_{0}', parameters.adh_sub_group) || '' }} / ${{ parameters.adh_subscription_type }})"
  condition: and(succeeded(), ne('${{ parameters.adh_group }}',''))

  jobs:
  - template: ../templates/job.powershell-with-az.yml
    parameters:
      displayName: 'RG Tags'
      variableGroup: modernization_tfstate_backend_details
      scriptPath: '$(Build.SourcesDirectory)/sanitychecks/scripts/Scan-RG-Tags.ps1'
      workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'

      arguments: >-
        -TenantId "$(tenant_id)"
        -ClientId "$(backend_client_id)"
        -ClientSecret "$(backend_client_secret)"
        -adh_group "${{ parameters.adh_group }}"
        -adh_sub_group "${{ parameters.adh_sub_group }}"            # <-- Added here
        -adh_subscription_type "${{ parameters.adh_subscription_type }}"
        -OutputDir "$(Build.ArtifactStagingDirectory)/rg-tags"
        -BranchName "$(Build.SourceBranchName)"

      artifactName: 'rg-tags'
      publishPath: '$(Build.ArtifactStagingDirectory)/rg-tags'
      poolName: ${{ parameters.poolName }}
      agentName: ${{ parameters.agentName }}
