trigger: none
pr: none

schedules:
  - cron: "0 */2 * * *"
    displayName: Sanity checks (ALL custodians) - every 2 hours
    branches:
      include:
        - test-sanitychecks
    always: true

variables:
  - group: modernization_tfstate_backend_details

pool:
  name: Self-Hosted-Pool

stages:
- stage: CustodianMonthlyScheduleStage
  displayName: "Custodian Monthly Schedule Stage"

  jobs:
  - job: allsubs_sanity
    displayName: "Run sanity checks across all custodians"
    timeoutInMinutes: 240

    steps:
    - checkout: self
      clean: true

    - task: PowerShell@2
      displayName: "Run sanity checks (ALL custodians)"
      # NOTE: keep this false if you want pipeline to succeed even if script returns nonzero.
      # But your script already supports -FailOnErrors:$false, so either is fine.
      continueOnError: true
      inputs:
        pwsh: true
        targetType: inline
        script: |
          $ErrorActionPreference = "Stop"

          Write-Host "TenantId : $(tenant_id)"
          Write-Host "ClientId : $(backend_client_id)"
          Write-Host "Secret   : present (hidden)"

          # Final artifact folder structure you want:
          # $(Build.ArtifactStagingDirectory)/SanityCheck_AllCustodian/All_Custodians/<custodian_env>/*
          $artifactBase = "$(Build.ArtifactStagingDirectory)/SanityCheck_AllCustodian"
          $artifactRoot = "$artifactBase/All_Custodians"
          New-Item -ItemType Directory -Path $artifactRoot -Force | Out-Null

          pwsh -NoProfile -File "$(Build.SourcesDirectory)/sanitychecks/scripts/Run-AllSubscriptions-Monthly.ps1" `
            -TenantId "$(tenant_id)" `
            -ClientId "$(backend_client_id)" `
            -ClientSecret "$(backend_client_secret)" `
            -SubscriptionsCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/subscriptions_master.csv" `
            -RgPermsNonPrdCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/nonprod_permissions.csv" `
            -RgPermsPrdCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/prod_permissions.csv" `
            -AdlsNonPrdInputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/adls_nonprd_permissions.csv" `
            -AdlsPrdInputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/adls_prd_permissions.csv" `
            -KvSecretsInputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/kvsecretsscan.csv" `
            -KvPermInputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/kvpermissions.csv" `
            -OutputRootDir "$artifactBase" `
            -RunFolderName "All_Custodians" `
            -FailOnErrors:$false `
            -RunRgPermissions:$true `
            -RunRgTags:$true `
            -RunKvSecrets:$true `
            -RunKvPermissions:$true `
            -RunKvFirewall:$true `
            -RunVnet:$true `
            -RunAdls:$true `
            -RunAdf:$true `
            -RunDatabricks:$true `
            -BranchName "$(Build.SourceBranchName)"

    - task: PublishPipelineArtifact@1
      displayName: "Publish outputs"
      condition: always()
      inputs:
        targetPath: "$(Build.ArtifactStagingDirectory)/SanityCheck_AllCustodian"
        artifact: "SanityCheck_AllCustodian"
