trigger: none
pr: none

schedules:
  - cron: "0 */2 * * *"
    displayName: Sanity checks (ALL custodians) - every 2 hours
    branches:
      include:
        - test-sanitychecks
    always: true

variables:
  - group: modernization_tfstate_backend_details

pool:
  name: Self-Hosted-Pool

stages:
- stage: CustodianMonthlyScheduleStage
  displayName: "Custodian Monthly Schedule Stage"

  jobs:
  - job: allsubs_sanity
    displayName: Run sanity checks across all custodians
    timeoutInMinutes: 240

    steps:
    - checkout: self
      clean: true

    - task: PowerShell@2
      displayName: Run sanity checks (ALL custodians)
      continueOnError: true
      inputs:
        pwsh: true
        targetType: inline
        script: |
          $ErrorActionPreference = "Stop"

          Write-Host "TenantId : $(tenant_id)"
          Write-Host "ClientId : $(backend_client_id)"
          Write-Host "Secret   : present (hidden)"

          $dateStamp = "$(Date:yyyyMMdd)"

          # Folder structure requested:
          # sanitychecks/out/SanityCheck_AllCustodians_YYYYMMDD/All_Custodians_YYYYMMDD/<BuildId>/...
          $repoRoot = "$(Build.SourcesDirectory)"
          $outRoot  = Join-Path $repoRoot "sanitychecks/out/SanityCheck_AllCustodians_$dateStamp/All_Custodians_$dateStamp/$(Build.BuildId)"
          New-Item -ItemType Directory -Path $outRoot -Force | Out-Null

          pwsh -NoProfile -File `
            "$repoRoot/sanitychecks/scripts/Run-AllSubscriptions-Monthly.ps1" `
            -TenantId "$(tenant_id)" `
            -ClientId "$(backend_client_id)" `
            -ClientSecret "$(backend_client_secret)" `
            -SubscriptionsCsvPath "$repoRoot/sanitychecks/inputs/subscriptions_master.csv" `
            -RgPermsNonPrdCsvPath "$repoRoot/sanitychecks/inputs/nonprod_permissions.csv" `
            -RgPermsPrdCsvPath "$repoRoot/sanitychecks/inputs/prod_permissions.csv" `
            -AdlsNonPrdInputCsvPath "$repoRoot/sanitychecks/inputs/adls_nonprd_permissions.csv" `
            -AdlsPrdInputCsvPath "$repoRoot/sanitychecks/inputs/adls_prd_permissions.csv" `
            -KvSecretsInputCsvPath "$repoRoot/sanitychecks/inputs/kvsecretsscan.csv" `
            -KvPermInputCsvPath "$repoRoot/sanitychecks/inputs/kvpermissions.csv" `
            -OutputRootDir $outRoot `
            -FailOnErrors:$false `
            -RunRgPermissions:$true `
            -RunRgTags:$true `
            -RunKvSecrets:$true `
            -RunKvPermissions:$true `
            -RunKvFirewall:$true `
            -RunVnet:$true `
            -RunAdls:$true `
            -RunAdf:$true `
            -RunDatabricks:$true `
            -BranchName "$(Build.SourceBranchName)"

    - task: PublishPipelineArtifact@1
      displayName: Publish outputs
      condition: always()
      inputs:
        targetPath: "$(Build.SourcesDirectory)/sanitychecks/out/SanityCheck_AllCustodians_$(Date:yyyyMMdd)"
        artifact: "SanityCheck_AllCustodians_$(Date:yyyyMMdd)"
