trigger: none
pr: none

schedules:
  # - cron: "30 2 1 * *"
  #   displayName: Monthly sanity checks (ALL custodians)
  #   branches:
  #     include:
  #       - main
  #   always: true

  - cron: "0 */2 * * *"
    displayName: Sanity checks (ALL custodians) - every 2 hours
    branches:
      include:
        - main
    always: true

variables:
  - group: modernization_tfstate_backend_details

pool:
  name: Self-Hosted-Pool

jobs:
- job: allsubs_sanity
  displayName: Run sanity checks across all custodians
  timeoutInMinutes: 240

  steps:
  - checkout: self
    clean: true

  - task: PowerShell@2
    displayName: Run sanity checks (ALL custodians)
    continueOnError: true
    inputs:
      pwsh: true
      targetType: inline
      script: |
        $ErrorActionPreference = "Stop"

        Write-Host "TenantId : $(tenant_id)"
        Write-Host "ClientId : $(backend_client_id)"
        Write-Host "Secret   : present (hidden)"

        $outRoot = "$(Build.SourcesDirectory)/sanitychecks/out/$(Build.BuildId)"
        New-Item -ItemType Directory -Path $outRoot -Force | Out-Null

        pwsh -NoProfile -File `
          "$(Build.SourcesDirectory)/sanitychecks/scripts/Run-AllSubscriptions-Monthly.ps1" `
          -TenantId "$(tenant_id)" `
          -ClientId "$(backend_client_id)" `
          -ClientSecret "$(backend_client_secret)" `
          -SubscriptionsCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/subscriptions_master.csv" `
          -RgPermsNonPrdCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/nonprod_permissions.csv" `
          -RgPermsPrdCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/prod_permissions.csv" `
          -AdlsNonPrdInputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/adls_nonprd_permissions.csv" `
          -AdlsPrdInputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/adls_prd_permissions.csv" `
          -KvSecretsInputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/kvsecretsscan.csv" `
          -KvPermInputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/kvpermissions.csv" `
          -OutputRootDir $outRoot `
          -FailOnErrors:$false `
          -RunRgPermissions:$true `
          -RunRgTags:$true `
          -RunKvSecrets:$true `
          -RunKvPermissions:$true `
          -RunKvFirewall:$true `
          -RunVnet:$true `
          -RunAdls:$true `
          -RunAdf:$true `
          -RunDatabricks:$true `
          -BranchName "$(Build.SourceBranchName)"


  - task: PublishPipelineArtifact@1
    displayName: Publish outputs
    inputs:
      targetPath: "$(Build.SourcesDirectory)/sanitychecks/out/$(Build.BuildId)"
      artifact: "sanitychecks_allsubs_$(Build.BuildId)"
