# stages/rg_permissions.stage.yml
# Minimal, no variable group, no agent pinning, safe artifact publishing

parameters:
  - name: adh_group
    type: string
    default: ''
  - name: adh_subscription_type
    type: string
    default: 'nonprd'   # values: nonprd | prd
  - name: poolName
    type: string
    default: 'Self-Hosted-Pool'
  - name: agentName
    type: string
    default: ''         # ignored in this minimal file (no demands)

stages:
- stage: rg_permissions
  displayName: "RG Permissions (ByCustodian)"
  jobs:
  - job: run_permission_check
    displayName: "Validate RG Permissions"
    pool:
      name: ${{ parameters.poolName }}

    steps:
    - checkout: self
      displayName: "Checkout repo"

    # Ensure outputs folder exists so PublishBuildArtifacts never errors
    - task: PowerShell@2
      displayName: "Prep outputs folder"
      inputs:
        targetType: inline
        pwsh: true
        script: |
          New-Item -ItemType Directory -Path "outputs" -Force | Out-Null

    # Run your scanner (adjust path if your script lives elsewhere)
    - task: PowerShell@2
      displayName: "Run Scan-RG-Permissions-ByCustodian.ps1"
      inputs:
        targetType: filePath
        filePath: scripts/Scan-RG-Permissions-ByCustodian.ps1
        arguments: >
          -adh_group "${{ parameters.adh_group }}"
          -adh_subscription_type "${{ parameters.adh_subscription_type }}"
        pwsh: true
        errorActionPreference: stop
        failOnStderr: false

    # Publish results (safe even if folder is empty)
    - task: PublishBuildArtifacts@1
      displayName: "Publish RG permission results"
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: "outputs"
        ArtifactName: "rg-permissions-results"
        publishLocation: "Container"
