parameters:
  adh_group: ''
  adh_subscription_type: 'nonprd'
  poolName: 'Self-Hosted-Pool'
  agentName: ''
  variableGroup: 'modernization_tfstate_backend_details'

stages:
- stage: RG_Tags
  displayName: "RG Tags (${{ parameters.adh_group }} / ${{ parameters.adh_subscription_type }})"
  jobs:
  - template: ../templates/job.powershell-with-az.yml
    parameters:
      variableGroup: ${{ parameters.variableGroup }}
      displayName: 'RG Tags Scan'
      scriptPath: 'sanitychecks/scripts/Scan-RG-Tags.ps1'
      workingDir:  '$(Build.SourcesDirectory)/sanitychecks/scripts'
      arguments: >-
        -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
        -adh_group "${{ parameters.adh_group }}" -adh_subscription_type "${{ parameters.adh_subscription_type }}"
        -OutputDir "$(Build.ArtifactStagingDirectory)/rg-tags" -BranchName "$(Build.SourceBranchName)"
      artifactName: 'rg-tags'
      publishPath:  '$(Build.ArtifactStagingDirectory)/rg-tags'
      poolType: self
      poolName: ${{ parameters.poolName }}
      agentName: ${{ parameters.agentName }}
