parameters:
  adh_group: ''
  adh_subscription_type: 'nonprd'
  poolName: 'Self-Hosted-Pool'
  agentName: ''
  variableGroup: 'modernization_tfstate_backend_details'

jobs:
- template: ../templates/job.powershell-with-az.yml
  parameters:
    variableGroup: ${{ parameters.variableGroup }}
    displayName: 'VNet & Peerings Scan'
    scriptPath: 'sanitychecks/scripts/Scan-VNet-Topology.ps1'
    workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
    arguments: >-
      -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
      -adh_group "${{ parameters.adh_group }}" -adh_subscription_type "${{ parameters.adh_subscription_type }}"
      -OutputDir "$(Build.ArtifactStagingDirectory)/vnet-topology" -BranchName "$(Build.SourceBranchName)"
    artifactName: "vnet-topology"
    publishPath: "$(Build.ArtifactStagingDirectory)/vnet-topology"
    poolName: ${{ parameters.poolName }}
    agentName: ${{ parameters.agentName }}
