parameters:
  adh_group: ''
  adh_subscription_type: 'nonprd'
  poolName: ''
  agentName: ''
  prodCsvPath: '$(Build.SourcesDirectory)/sanitychecks/inputs/prod_permissions.csv'
  nonProdCsvPath: '$(Build.SourcesDirectory)/sanitychecks/inputs/nonprod_permissions.csv'

stages:
- stage: RG_Permissions
  displayName: "RG Permissions (${{ parameters.adh_group }} / ${{ parameters.adh_subscription_type }})"
  jobs:
  - template: ../templates/job.powershell-with-az.yml
    parameters:
      displayName: 'Run RG Permissions Scan'
      variableGroup: modernization_tfstate_backend_details
      workingDir:  '$(Build.SourcesDirectory)/sanitychecks/scripts'
      scriptPath:  'sanitychecks/scripts/Scan-RG-Permissions-ByCustodian.ps1'
      arguments: >-
        -TenantId "$(tenant_id)"
        -ClientId "$(backend_client_id)"
        -ClientSecret "$(backend_client_secret)"
        -adh_group "${{ parameters.adh_group }}"
        -adh_subscription_type "${{ parameters.adh_subscription_type }}"
        -OutputDir "$(Build.ArtifactStagingDirectory)/rg-permissions"
        -BranchName "$(Build.SourceBranchName)"
        -ProdCsvPath "${{ parameters.prodCsvPath }}"
        -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
      artifactName: 'rg-permissions'
      publishPath:  '$(Build.ArtifactStagingDirectory)/rg-permissions'
      poolName:     ${{ parameters.poolName }}
      agentName:    ${{ parameters.agentName }}
