parameters:
  - name: adh_group
    type: string
    default: ''
  - name: adh_subscription_type
    type: string
    default: nonprd
    values: [nonprd, prd]
  - name: poolName
    type: string
    default: 'Self-Hosted-Pool'
  - name: agentName
    type: string
    default: ''

stages:
- stage: rg_permissions
  displayName: "RG Permissions (ByCustodian)"
  condition: and(succeeded(), ne('${{ parameters.adh_group }}',''))
  jobs:
  - job: scan_rg_permissions
    displayName: "Scan RG Permissions: ${{ parameters.adh_group }} (${{ parameters.adh_subscription_type }})"
    pool:
      name: ${{ parameters.poolName }}
      demands:
      - Agent.Name -equals ${{ parameters.agentName }}

    steps:
    - checkout: self
      clean: true

    # Optional: prove the CSVs exist where we point the script
    - task: PowerShell@2
      displayName: "Debug: check CSVs"
      inputs:
        targetType: inline
        pwsh: true
        script: |
          $prod = "$(Build.SourcesDirectory)/sanitychecks/inputs/prod_permissions.csv"
          $nonp = "$(Build.SourcesDirectory)/sanitychecks/inputs/nonprod_permissions.csv"
          Write-Host "ProdCsvPath    = $prod"
          Write-Host "NonProdCsvPath = $nonp"
          if (-not (Test-Path -LiteralPath $prod)) { Write-Error "prod_permissions.csv not found at $prod" }
          if (-not (Test-Path -LiteralPath $nonp)) { Write-Error "nonprod_permissions.csv not found at $nonp" }

    - task: PowerShell@2
      displayName: "Run RG Permissions Scan"
      inputs:
        targetType: filePath
        filePath: "$(Build.SourcesDirectory)/sanitychecks/scripts/Scan-RG-Permissions-ByCustodian.ps1"
        arguments: >
          -TenantId "$(tenant_id)"
          -ClientId "$(backend_client_id)"
          -ClientSecret "$(backend_client_secret)"
          -adh_group "${{ parameters.adh_group }}"
          -adh_subscription_type "${{ parameters.adh_subscription_type }}"
          -ProdCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/prod_permissions.csv"
          -NonProdCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/nonprod_permissions.csv"
          -OutputDir "$(Build.ArtifactStagingDirectory)/rg-permissions"
          -BranchName "$(Build.SourceBranchName)"
        pwsh: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish RG Permissions"
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/rg-permissions"
        ArtifactName: "rg-permissions"
