parameters:
  adh_group: ''
  adh_subscription_type: 'nonprd'
  poolName: 'Self-Hosted-Pool'
  agentName: ''
  variableGroup: 'modernization_tfstate_backend_details'

stages:
- stage: ADLS_ACL_Validation
  displayName: "ADLS ACL Validation (${{ parameters.adh_group }} / ${{ parameters.adh_subscription_type }})"

  jobs:
  - template: ../templates/job.powershell-with-az.yml
    parameters:
      variableGroup: ${{ parameters.variableGroup }}
      displayName: 'ADLS ACL Validation'
      scriptPath: '$(Build.SourcesDirectory)/sanitychecks/scripts/Scan-ADLS-Acls.ps1'
      workingDir:  '$(Build.SourcesDirectory)/sanitychecks/scripts'
      arguments: >-
        -TenantId "$(tenant_id)"
        -ClientId "$(backend_client_id)"
        -ClientSecret "$(backend_client_secret)"
        -adh_group "${{ parameters.adh_group }}"
        -adh_sub_group ""                             # or 'OPX' / 'SVS' when you need it
        -adh_subscription_type "${{ parameters.adh_subscription_type }}"
        -InputCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/adls_nonprd_permissions.csv"
        -OutputDir "$(Build.ArtifactStagingDirectory)/adls-acl"
        -BranchName "$(Build.SourceBranchName)"
      poolType: self
      poolName: ${{ parameters.poolName }}
      agentName: ${{ parameters.agentName }}
      artifactName: 'adls-acl'
      publishPath: '$(Build.ArtifactStagingDirectory)/adls-acl'
