parameters:
  - name: adh_group
    type: string
    default: ''

  # OPTIONAL – can be left empty; PS1 will trim spaces
  - name: adh_sub_group
    type: string
    default: ''

  - name: adh_subscription_type
    type: string
    default: nonprd
    values: [nonprd, prd]

  - name: poolName
    type: string
    default: 'Self-Hosted-Pool'

  - name: agentName
    type: string
    default: ''

stages:
- stage: kv_permissions
  displayName: ${{ format('KV Permissions ({0} / {1})', parameters.adh_group, parameters.adh_subscription_type) }}
  condition: and(succeeded(), ne('${{ parameters.adh_group }}',''))

  variables:
    - group: modernization_tfstate_backend_details   # tenant_id, backend_client_id, etc.

  jobs:
  - job: kv_permissions_job
    pool:
      name: ${{ parameters.poolName }}
      demands:
        - agent.name -equals ${{ parameters.agentName }}

    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'KV Permissions'
        inputs:
          targetType: 'filePath'
          filePath: '$(Build.SourcesDirectory)/sanitychecks/scripts/Scan-KV-Permissions.ps1'
          workingDirectory: '$(Build.SourcesDirectory)/sanitychecks/scripts'
          arguments: >
            -TenantId "$(tenant_id)"
            -ClientId "$(backend_client_id)"
            -ClientSecret "$(backend_client_secret)"
            -adh_group "${{ parameters.adh_group }}"
            -adh_sub_group "${{ parameters.adh_sub_group }}"
            -adh_subscription_type "${{ parameters.adh_subscription_type }}"
            -KvPermCsvPath "$(Build.SourcesDirectory)/sanitychecks/inputs/kvpermissions.csv"
            -OutputDir "$(Build.ArtifactStagingDirectory)/kv-perms"
            -BranchName "$(Build.SourceBranchName)"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/kv-perms'
          ArtifactName: 'kv-perms'
          publishLocation: 'Container'
