parameters:
  variableGroup: 'modernization_tfstate_backend_details'
  displayName: ''
  scriptPath: ''
  workingDir: ''
  arguments: ''
  artifactName: ''
  publishPath: ''
  poolName: 'Self-Hosted-Pool'
  agentName: ''

jobs:
- job: run_script
  displayName: ${{ parameters.displayName }}
  pool:
    name: ${{ parameters.poolName }}
    ${{ if ne(parameters.agentName, '') }}:
      demands:
      - Agent.Name -equals ${{ parameters.agentName }}

  variables:
  - group: ${{ parameters.variableGroup }}

  steps:
  - checkout: self
    clean: true

  # -------------------------------------------------------
  # ✅ HARD RESET: prevents random default subscription = 0000...
  # Safe on self-hosted Windows agents running as service (systemprofile)
  # -------------------------------------------------------
  - task: PowerShell@2
    displayName: "HARD RESET: Az + CLI contexts (pre-scan)"
    inputs:
      targetType: inline
      pwsh: true
      workingDirectory: ${{ parameters.workingDir }}
      script: |
        Write-Host "=== HARD RESET (pre-scan) ==="
        Write-Host "Agent: $env:AGENT_NAME"
        Write-Host "USERPROFILE: $env:USERPROFILE"
        Write-Host "LOCALAPPDATA: $env:LOCALAPPDATA"
        Write-Host "AZURE_CONFIG_DIR: $env:AZURE_CONFIG_DIR"

        # ----------------------------
        # Azure CLI logout (best effort)
        # ----------------------------
        try { az logout | Out-Null } catch { Write-Host "az logout skipped" }

        Import-Module Az.Accounts -ErrorAction Stop

        # ----------------------------
        # Az PowerShell context reset
        # ----------------------------
        Disable-AzContextAutosave -Scope Process     -ErrorAction SilentlyContinue | Out-Null
        Disable-AzContextAutosave -Scope CurrentUser -ErrorAction SilentlyContinue | Out-Null

        Disconnect-AzAccount -Scope Process     -ErrorAction SilentlyContinue | Out-Null
        Disconnect-AzAccount -Scope CurrentUser -ErrorAction SilentlyContinue | Out-Null

        Clear-AzContext -Scope Process     -Force -ErrorAction SilentlyContinue | Out-Null
        Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue | Out-Null

        # ----------------------------
        # SAFE cache cleanup (avoid USERPROFILE on systemprofile agents)
        # ----------------------------
        $pathsToRemove = @()

        # Azure CLI cache dir (if set)
        if (-not [string]::IsNullOrWhiteSpace($env:AZURE_CONFIG_DIR)) {
          $pathsToRemove += $env:AZURE_CONFIG_DIR
        }

        # Az PowerShell / Azure SDK cache under LOCALAPPDATA
        if (-not [string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) {
          $pathsToRemove += (Join-Path $env:LOCALAPPDATA "Azure")
        }

        foreach ($p in $pathsToRemove) {
          if (Test-Path -LiteralPath $p) {
            Write-Host "Removing Azure cache: $p"
            Remove-Item -LiteralPath $p -Recurse -Force -ErrorAction SilentlyContinue
          } else {
            Write-Host "Cache path not found (skipped): $p"
          }
        }

        # ----------------------------
        # Debug: show any remaining context
        # ----------------------------
        try {
          $ctx = Get-AzContext -ErrorAction SilentlyContinue
          if ($ctx -and $ctx.Subscription) {
            Write-Host "WARNING: Context still present after reset: $($ctx.Subscription.Id) / $($ctx.Subscription.Name)"
          } else {
            Write-Host "Az context cleared successfully."
          }
        } catch {}

        Write-Host "=== HARD RESET done ==="

  - task: PowerShell@2
    displayName: Prepare output dir
    inputs:
      targetType: inline
      pwsh: true
      script: |
        $out = "${{ parameters.publishPath }}"
        if ([string]::IsNullOrWhiteSpace($out)) { throw "publishPath is empty." }
        if (-not (Test-Path -LiteralPath $out)) {
          New-Item -ItemType Directory -Path $out -Force | Out-Null
        }
        Write-Host "Output: $out"

  - task: PowerShell@2
    displayName: Run ${{ parameters.scriptPath }}
    inputs:
      targetType: filePath
      filePath: ${{ parameters.scriptPath }}
      workingDirectory: ${{ parameters.workingDir }}
      arguments: ${{ parameters.arguments }}
      pwsh: true
    env:
      AZURE_CORE_ONLY_SHOW_ERRORS: '1'

  - task: PublishBuildArtifacts@1
    displayName: Publish ${{ parameters.artifactName }}
    inputs:
      PathtoPublish: ${{ parameters.publishPath }}
      ArtifactName: ${{ parameters.artifactName }}
