parameters:
  variableGroup: 'modernization_tfstate_backend_details'
  displayName: ''
  scriptPath: ''
  workingDir: ''
  arguments: ''
  artifactName: ''
  publishPath: ''
  poolName: 'Self-Hosted-Pool'
  agentName: ''

jobs:
- job: run_script
  displayName: ${{ parameters.displayName }}
  pool:
    name: ${{ parameters.poolName }}
    ${{ if ne(parameters.agentName, '') }}:
      demands:
      - Agent.Name -equals ${{ parameters.agentName }}

  variables:
  - group: ${{ parameters.variableGroup }}

  steps:
  - checkout: self
    clean: true

  # -------------------------------------------------------
  # ✅ HARD RESET (SAFE): isolate + clear Az + Azure CLI contexts
  # - Does NOT fail if "az logout" says "no active accounts"
  # - Forces per-job Azure CLI profile dir to avoid cross-run contamination
  # - Clears Az contexts autosave in both scopes
  # -------------------------------------------------------
  - task: PowerShell@2
    displayName: "HARD RESET: Az + CLI contexts (pre-scan)"
    inputs:
      targetType: inline
      pwsh: true
      workingDirectory: ${{ parameters.workingDir }}
      script: |
        Write-Host "=== HARD RESET (pre-scan) ==="
        Write-Host "Agent: $env:AGENT_NAME"
        Write-Host "USERPROFILE: $env:USERPROFILE"
        Write-Host "Agent.TempDirectory: $env:AGENT_TEMPDIRECTORY"

        # 1) Isolate Azure CLI profile per job (prevents random cached contexts)
        $jobAzureDir = Join-Path $env:AGENT_TEMPDIRECTORY "azure_config"
        New-Item -ItemType Directory -Path $jobAzureDir -Force | Out-Null
        $env:AZURE_CONFIG_DIR = $jobAzureDir
        Write-Host "AZURE_CONFIG_DIR set to: $env:AZURE_CONFIG_DIR"

        # 2) Azure CLI logout (best effort) - DO NOT FAIL job if it returns nonzero
        if (Get-Command az -ErrorAction SilentlyContinue) {
          az logout | Out-Null
          if ($LASTEXITCODE -ne 0) {
            Write-Host "az logout returned exit code $LASTEXITCODE (ignored)."
            $global:LASTEXITCODE = 0
          } else {
            Write-Host "az logout OK."
          }

          # Clear cli account cache best-effort
          az account clear | Out-Null
          if ($LASTEXITCODE -ne 0) {
            Write-Host "az account clear returned exit code $LASTEXITCODE (ignored)."
            $global:LASTEXITCODE = 0
          } else {
            Write-Host "az account clear OK."
          }
        } else {
          Write-Host "Azure CLI not found on agent - skipping az logout."
        }

        # 3) Az PowerShell context reset
        Import-Module Az.Accounts -ErrorAction Stop

        Disable-AzContextAutosave -Scope Process     -ErrorAction SilentlyContinue | Out-Null
        Disable-AzContextAutosave -Scope CurrentUser -ErrorAction SilentlyContinue | Out-Null

        Disconnect-AzAccount -Scope Process     -ErrorAction SilentlyContinue | Out-Null
        Disconnect-AzAccount -Scope CurrentUser -ErrorAction SilentlyContinue | Out-Null

        Clear-AzContext -Scope Process     -Force -ErrorAction SilentlyContinue | Out-Null
        Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue | Out-Null

        # Clear DefaultSubscriptionForLogin if set
        try {
          $cfg = Get-AzConfig -ErrorAction SilentlyContinue | Where-Object Name -like '*DefaultSubscriptionForLogin*'
          if ($cfg) {
            Write-Host "Existing DefaultSubscriptionForLogin: $($cfg.Value)"
            Update-AzConfig -DefaultSubscriptionForLogin '' | Out-Null
            Write-Host "DefaultSubscriptionForLogin cleared."
          } else {
            Write-Host "No DefaultSubscriptionForLogin set."
          }
        } catch {
          Write-Host "Get/Update-AzConfig skipped: $($_.Exception.Message)"
        }

        # Remove subscription env vars that can poison runs
        foreach ($k in @('AZURE_SUBSCRIPTION_ID','ARM_SUBSCRIPTION_ID','AZURE_SUBSCRIPTION','ARM_SUBSCRIPTION')) {
          if (Test-Path "env:$k") {
            $old = (Get-Item "env:$k").Value
            Write-Host "Removing env:$k (was '$old')"
            Remove-Item "env:$k" -ErrorAction SilentlyContinue
          }
        }

        # Debug: prove context is clear
        try {
          $ctx = Get-AzContext -ErrorAction SilentlyContinue
          if ($ctx -and $ctx.Subscription) {
            Write-Host "WARNING: Context still present after reset: $($ctx.Subscription.Id) / $($ctx.Subscription.Name)"
          } else {
            Write-Host "Az context cleared successfully."
          }
        } catch {}

        Write-Host "=== HARD RESET done ==="
    env:
      AZURE_CORE_ONLY_SHOW_ERRORS: '1'

  - task: PowerShell@2
    displayName: Prepare output dir
    inputs:
      targetType: inline
      pwsh: true
      script: |
        $out = "${{ parameters.publishPath }}"
        if ([string]::IsNullOrWhiteSpace($out)) { throw "publishPath is empty." }
        if (-not (Test-Path -LiteralPath $out)) {
          New-Item -ItemType Directory -Path $out -Force | Out-Null
        }
        Write-Host "Output: $out"

  - task: PowerShell@2
    displayName: Run ${{ parameters.scriptPath }}
    inputs:
      targetType: filePath
      filePath: ${{ parameters.scriptPath }}
      workingDirectory: ${{ parameters.workingDir }}
      arguments: ${{ parameters.arguments }}
      pwsh: true
    env:
      # keep CLI isolated for the script task too
      AZURE_CORE_ONLY_SHOW_ERRORS: '1'
      AZURE_CONFIG_DIR: '$(Agent.TempDirectory)\azure_config'

  - task: PublishBuildArtifacts@1
    displayName: Publish ${{ parameters.artifactName }}
    inputs:
      PathtoPublish: ${{ parameters.publishPath }}
      ArtifactName: ${{ parameters.artifactName }}
