trigger: none
pr: none

parameters:
  # -------------------------
  # Core inputs
  # -------------------------
  - name: adh_group
    type: string
    default: ''

  # OPTIONAL – can be left blank when not used (KTK only, etc.)
  # Default is a single space so the UI doesn't block the Run button,
  # but we normalize it to '' in variables.
  - name: adh_sub_group
    type: string
    default: ' '

  - name: adh_subscription_type
    type: string
    default: nonprd
    values:
      - nonprd
      - prd

  - name: poolSuffix
    type: string
    default: '_agent1'
    values:
      - '_agent1'
      - '_agent2'
      - '_agent3'

  - name: poolName
    type: string
    default: 'Self-Hosted-Pool'

  # ✅ OPTIONAL: override exact agent name (leave blank to use default naming)
  # NOTE: Use a single space as default so ADO UI doesn't mark it "Required".
  - name: custom_agent_name
    type: string
    default: ' '

  # -------------------------
  # Stage toggles
  # -------------------------
  - name: run_all_stages
    type: boolean
    default: true

  - name: run_rg_permissions
    type: boolean
    default: false

  - name: run_rg_tags
    type: boolean
    default: false

  - name: run_kv_secrets
    type: boolean
    default: false

  - name: run_kv_permissions
    type: boolean
    default: false

  - name: run_kv_firewall
    type: boolean
    default: false

  - name: run_vnet
    type: boolean
    default: false

  - name: run_adf
    type: boolean
    default: false

  - name: run_adls
    type: boolean
    default: false

  - name: run_databricks
    type: boolean
    default: false


variables:
  # Normalize adh_sub_group: remove all spaces so " " becomes ""
  - name: adh_sub_group_normalized
    value: ${{ replace(parameters.adh_sub_group, ' ', '') }}

  # ✅ Normalize custom agent name too (so default " " becomes "")
  - name: custom_agent_name_normalized
    value: ${{ replace(parameters.custom_agent_name, ' ', '') }}

  # ✅ Compile-time safe agentName with optional override support
  - ${{ if ne(variables.custom_agent_name_normalized, '') }}:
      - name: agentName
        value: ${{ variables.custom_agent_name_normalized }}
  - ${{ else }}:
      - name: agentName
        value: ${{ format('{0}_{1}{2}', parameters.adh_group, parameters.adh_subscription_type, parameters.poolSuffix) }}


stages:
  # -------------------------------------------------------
  # 0. Az context cleanup (KEEP THIS – IMPORTANT)
  # -------------------------------------------------------
  - stage: az_context_cleanup
    displayName: "Az context cleanup on agent"
    condition: and(succeeded(), ne('${{ parameters.adh_group }}',''))
    jobs:
      - job: cleanup_az_context
        displayName: "Cleanup Az contexts and defaults"
        pool:
          name: ${{ parameters.poolName }}
          demands:
            - Agent.Name -equals ${{ variables.agentName }}

        steps:
          - checkout: self

          - task: PowerShell@2
            displayName: "Reset Az context and default subscription"
            inputs:
              targetType: inline
              pwsh: true
              script: |
                Write-Host "=== Az context cleanup start ==="
                Write-Host "Agent selected (expected): $(agentName)"
                Write-Host "Agent actually running: $env:AGENT_NAME"

                Import-Module Az.Accounts -ErrorAction Stop

                # Disable autosave for this process
                Disable-AzContextAutosave -Scope Process | Out-Null

                # Clear any current in-process context
                Clear-AzContext -Scope Process -Force -ErrorAction SilentlyContinue | Out-Null

                # Clear bad DefaultSubscriptionForLogin if present
                $cfg = Get-AzConfig | Where-Object Name -like '*DefaultSubscriptionForLogin*'
                if ($cfg) {
                  Write-Host "Existing DefaultSubscriptionForLogin: $($cfg.Value)"
                  Update-AzConfig -DefaultSubscriptionForLogin '' | Out-Null
                  Write-Host "DefaultSubscriptionForLogin cleared."
                } else {
                  Write-Host "No DefaultSubscriptionForLogin set at Az config level."
                }

                # Remove subscription-related env vars if they exist
                foreach ($k in @(
                  'AZURE_SUBSCRIPTION_ID',
                  'ARM_SUBSCRIPTION_ID',
                  'AZURE_SUBSCRIPTION',
                  'ARM_SUBSCRIPTION'
                )) {
                  if (Test-Path "env:$k") {
                    $old = (Get-Item "env:$k").Value
                    Write-Host "Removing env:$k (was '$old')"
                    Remove-Item "env:$k" -ErrorAction SilentlyContinue
                  }
                }

                Write-Host "=== Az context cleanup done ==="


  # -------------------------------------------------------
  # 1. Agent diagnostics
  # -------------------------------------------------------
  - stage: agent_injection_check
    displayName: "Agent Parameter Injection and Diagnostics"
    condition: and(succeeded(), ne('${{ parameters.adh_group }}',''))
    jobs:
      - job: test_param_injection
        displayName: "PowerShell Parameter and Environment Check"
        pool:
          name: ${{ parameters.poolName }}
          demands:
            - Agent.Name -equals ${{ variables.agentName }}

        steps:
          - checkout: self

          # Diagnostic 0: Confirm selected agent
          - task: PowerShell@2
            displayName: "Confirm selected agent"
            inputs:
              targetType: inline
              pwsh: true
              script: |
                Write-Host "Agent selected (expected): $(agentName)"
                Write-Host "Agent actually running: $env:AGENT_NAME"

          # Diagnostic 1: Test for global parameter injection
          - task: PowerShell@2
            displayName: "Test Minimal PowerShell Script"
            inputs:
              targetType: inline
              pwsh: true
              script: |
                Write-Host "If this runs, agent is not injecting unwanted parameters."

          # Diagnostic 2: List environment variables
          - task: PowerShell@2
            displayName: "List Environment Variables"
            inputs:
              targetType: inline
              pwsh: true
              script: |
                Write-Host "=== Agent Environment Variables ==="
                Get-ChildItem Env: | Sort-Object Name | Format-Table -AutoSize

          # Diagnostic 3: List all possible profile/init scripts
          - task: PowerShell@2
            displayName: "List Profile and Init Scripts"
            inputs:
              targetType: inline
              pwsh: true
              script: |
                $paths = @(
                  "$env:USERPROFILE\Documents\WindowsPowerShell\profile.ps1",
                  "$env:USERPROFILE\Documents\PowerShell\profile.ps1",
                  "C:\agent\profile.ps1",
                  "C:\agent\init.ps1"
                )
                foreach ($path in $paths) {
                  if (Test-Path $path) {
                    Write-Host "=== Found: $path ==="
                    Get-Content $path
                    Write-Host ""
                  }
                }


  # -------------------------------------------------------
  # 2. RG Permissions
  # -------------------------------------------------------
  - ${{ if or(eq(parameters.run_all_stages, true), eq(parameters.run_rg_permissions, true)) }}:
    - template: stages/rg_permissions.stage.yml
      parameters:
        adh_group:             ${{ parameters.adh_group }}
        adh_sub_group:         ${{ variables.adh_sub_group_normalized }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        poolName:              ${{ parameters.poolName }}
        agentName:             ${{ variables.agentName }}


  # -------------------------------------------------------
  # 3. RG Tags
  # -------------------------------------------------------
  - ${{ if or(eq(parameters.run_all_stages, true), eq(parameters.run_rg_tags, true)) }}:
    - template: stages/rg_tags.stage.yml
      parameters:
        adh_group:             ${{ parameters.adh_group }}
        adh_sub_group:         ${{ variables.adh_sub_group_normalized }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        poolName:              ${{ parameters.poolName }}
        agentName:             ${{ variables.agentName }}


  # -------------------------------------------------------
  # 4. Key Vault Secrets
  # -------------------------------------------------------
  - ${{ if or(eq(parameters.run_all_stages, true), eq(parameters.run_kv_secrets, true)) }}:
    - template: stages/kv_secrets.stage.yml
      parameters:
        adh_group:             ${{ parameters.adh_group }}
        adh_sub_group:         ${{ variables.adh_sub_group_normalized }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        poolName:              ${{ parameters.poolName }}
        agentName:             ${{ variables.agentName }}


  # -------------------------------------------------------
  # 5. Key Vault Permissions
  # -------------------------------------------------------
  - ${{ if or(eq(parameters.run_all_stages, true), eq(parameters.run_kv_permissions, true)) }}:
    - template: stages/kv_permissions.stage.yml
      parameters:
        adh_group:             ${{ parameters.adh_group }}
        adh_sub_group:         ${{ variables.adh_sub_group_normalized }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        poolName:              ${{ parameters.poolName }}
        agentName:             ${{ variables.agentName }}


  # -------------------------------------------------------
  # 6. Key Vault Firewall
  # -------------------------------------------------------
  - ${{ if or(eq(parameters.run_all_stages, true), eq(parameters.run_kv_firewall, true)) }}:
    - template: stages/kv_firewall.stage.yml
      parameters:
        adh_group:             ${{ parameters.adh_group }}
        adh_sub_group:         ${{ variables.adh_sub_group_normalized }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        poolName:              ${{ parameters.poolName }}
        agentName:             ${{ variables.agentName }}


  # -------------------------------------------------------
  # 7. VNet / Network
  # -------------------------------------------------------
  - ${{ if or(eq(parameters.run_all_stages, true), eq(parameters.run_vnet, true)) }}:
    - template: stages/vnet.stage.yml
      parameters:
        adh_group:             ${{ parameters.adh_group }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        poolName:              ${{ parameters.poolName }}
        agentName:             ${{ variables.agentName }}


  # -------------------------------------------------------
  # 8. Data Factory
  # -------------------------------------------------------
  - ${{ if or(eq(parameters.run_all_stages, true), eq(parameters.run_adf, true)) }}:
    - template: stages/adf.stage.yml
      parameters:
        adh_group:             ${{ parameters.adh_group }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        poolName:              ${{ parameters.poolName }}
        agentName:             ${{ variables.agentName }}


  # -------------------------------------------------------
  # 9. ADLS Validation
  # -------------------------------------------------------
  - ${{ if or(eq(parameters.run_all_stages, true), eq(parameters.run_adls, true)) }}:
    - template: stages/adls.stage.yml
      parameters:
        adh_group:             ${{ parameters.adh_group }}
        adh_sub_group:         ${{ variables.adh_sub_group_normalized }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        poolName:              ${{ parameters.poolName }}
        agentName:             ${{ variables.agentName }}


  # -------------------------------------------------------
  # 10. Databricks Scan
  # -------------------------------------------------------
  - ${{ if or(eq(parameters.run_all_stages, true), eq(parameters.run_databricks, true)) }}:
    - template: stages/databricks.stage.yml
      parameters:
        adh_group:             ${{ parameters.adh_group }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        poolName:              ${{ parameters.poolName }}
        agentName:             ${{ variables.agentName }}
